import {
  CardAttachLocation,
  CounterTokenType,
} from "../../constants/card-constants";
import { GameProperties } from "../GameModule";

export const properties: GameProperties = {
  deckSite: "",
  decklistApi: "",
  decklistSearchApi: "",
  allowSpecificCardSearch: true,
  decklistSearchApiConstants: "",
  encounterUiName: "Card Sets",
  initialPlaymatImageLocation:
    "/images/from_modules/marvel-legendary/spiderman-legendary.png",
  customPlaymatWidth: 1440,
  possibleIcons: [],
  modifiers: [],
  tokens: {
    stunned: null,
    confused: null,
    tough: null,
    damage: null,
    threat: null,
    generic: null,
    acceleration: null,
  },
  iconCounters: [],
  useAltCardArtByDefault: true,
  defaultAttachLocation: CardAttachLocation.UpAndRight,
  tableCardSlots: [
    { landscape: false, relativeX: 143, relativeY: 205 },
    { landscape: false, relativeX: 315, relativeY: 205 },
    { landscape: false, relativeX: 492, relativeY: 205 },
    { landscape: false, relativeX: 1220, relativeY: 202 },
    { landscape: false, relativeX: 1399, relativeY: 201 },
    { landscape: false, relativeX: 143, relativeY: 485 },
    { landscape: false, relativeX: 315, relativeY: 485 },
    { landscape: false, relativeX: 1399, relativeY: 481 },
    { landscape: false, relativeX: 143, relativeY: 766 },
    { landscape: false, relativeX: 315, relativeY: 766 },
    { landscape: false, relativeX: 1399, relativeY: 762 },
    { landscape: false, relativeX: 1214, relativeY: 476 },
    { landscape: false, relativeX: 1033, relativeY: 476 },
    { landscape: false, relativeX: 858, relativeY: 476 },
    { landscape: false, relativeX: 681, relativeY: 476 },
    { landscape: false, relativeX: 502, relativeY: 476 },
    { landscape: false, relativeX: 1214, relativeY: 757 },
    { landscape: false, relativeX: 1033, relativeY: 757 },
    { landscape: false, relativeX: 858, relativeY: 757 },
    { landscape: false, relativeX: 681, relativeY: 757 },
    { landscape: false, relativeX: 502, relativeY: 757 },
  ],
};
